server.port =8081
message=Chao mung ban den voi Server tu Config Server
# spring.datasource.url=jdbc:postgresql://localhost:5432/mic_session06db?currentSchema=patientdb
# spring.datasource.username=postgres
# spring.datasource.password=000000

app.welcome=Chao mung toi BV RikkeiEducation

spring.datasource.driver-class-name=org.postgresql.Driver